In [9]:
import numpy as np
np.__version__

'1.16.5'

In [11]:
a = np.arange(0,21,1) #第一題
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [12]:
a_2 = a[::2] #第二題
print(a_2)

[ 0  2  4  6  8 10 12 14 16 18 20]


In [13]:
a_3 = a[::3] #第三題
print(a_3)

[ 0  3  6  9 12 15 18]
